# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-01 18:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='dateadded',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='dateupdated',
        ),
    ]
